### ISSUE TITLE
sqlresolvererror

### ISSUE THREAD

**Issue by heket87** [kheeklab/privacyidea-docker#72]
after container restart pass of sqlresolver changed to default. How to fix it?

**Comment by mr-ssd** [comment]
Hi, @heket87 thank you for reporting the issue. I'll check the issue, but it would be helpful if you could share the reproduce steps.

**Comment by mr-ssd** [comment]
Hi @heket87 after checking the possible root cause is that the key file that used to encrypt/decrypt  password and token has been changed after restart. 
Make sure you backup encrypt file and keep it persistent on each restart by mount it to host or in volume. The default location of the file is `/data/privacyidea/keys/encfile`
